#ifndef WOLFSSL_USER_SETTINGS
#define WOLFSSL_USER_SETTINGS
#endif

#include <sdkconfig.h>

#define WOLFSSL_ESPIDF
#define WOLFSSL_ESP32

#define NO_RSA
#define WC_RSA_BLINDING
#define NO_DH
#define NO_DSA
#define NO_RC4
#define NO_MD4
#define NO_FILESYSTEM
#define NO_OLD_TLS

#define WOLFSSL_TLS13
#define HAVE_TLS_EXTENSIONS
#define HAVE_HKDF
#define HAVE_AEAD
#define HAVE_SUPPORTED_CURVES
#define HAVE_AESGCM

#define HAVE_ECC
//#define HAVE_CURVE25519

#define WOLFSSL_SHA384
#define WOLFSSL_SMALL_STACK

#define USE_FAST_MATH
#define TFM_TIMING_RESISTANT


//#define WOLFSSL_PQC_HYBRIDS
#define WOLFSSL_SHA3
#define WOLFSSL_SHAKE128
#define WOLFSSL_SHAKE256
#define WOLFSSL_MLKEM_SMALL
#define WOLFSSL_HAVE_MLKEM
#define WOLFSSL_WC_MLKEM


#define HAVE_QSH


#if defined(CONFIG_IDF_TARGET_ESP32S3)
    #define NO_ESP32_CRYPT
    #define NO_WOLFSSL_ESP32_CRYPT_HASH
    #define NO_WOLFSSL_ESP32_CRYPT_AES
    #define NO_WOLFSSL_ESP32_CRYPT_RSA_PRI
    #define NO_WOLFSSL_ESP32_CRYPT_RSA_PRI_MP_MUL
    #define NO_WOLFSSL_ESP32_CRYPT_RSA_PRI_MULMOD
    #define NO_WOLFSSL_ESP32_CRYPT_RSA_PRI_EXPTMOD
#else
    #define NO_ESP32_CRYPT
    #define NO_WOLFSSL_ESP32_CRYPT_HASH
    #define NO_WOLFSSL_ESP32_CRYPT_AES
    #define NO_WOLFSSL_ESP32_CRYPT_RSA_PRI
#endif